"""add_hashed_password_to_users

Revision ID: 467b998fb50e
Revises: d17e113f3a23
Create Date: 2026-05-15 03:59:37.646066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467b998fb50e'
down_revision: Union[str, None] = 'd17e113f3a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default='', comment='密码哈希（bcrypt）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
