"""init: users, auth, subscriptions, quotas, question_records

Revision ID: d17e113f3a23
Revises: 
Create Date: 2026-05-15 02:59:03.304589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17e113f3a23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_daily_quota_user_date', 'daily_quotas', ['user_id', 'date'])
    op.alter_column('question_records', 'question_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('user_auth', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='凭证过期时间（验证码有效期为 5 分钟）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'expires_at')
    op.alter_column('question_records', 'question_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint('uq_daily_quota_user_date', 'daily_quotas', type_='unique')
    # ### end Alembic commands ###
